/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegionsRouteImport } from './routes/regions'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as FarmersRouteImport } from './routes/farmers'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'

const RegionsRoute = RegionsRouteImport.update({
  id: '/regions',
  path: '/regions',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmersRoute = FarmersRouteImport.update({
  id: '/farmers',
  path: '/farmers',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/assistant': typeof AssistantRoute
  '/farmers': typeof FarmersRoute
  '/inventory': typeof InventoryRoute
  '/regions': typeof RegionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/assistant': typeof AssistantRoute
  '/farmers': typeof FarmersRoute
  '/inventory': typeof InventoryRoute
  '/regions': typeof RegionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/assistant': typeof AssistantRoute
  '/farmers': typeof FarmersRoute
  '/inventory': typeof InventoryRoute
  '/regions': typeof RegionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/assistant'
    | '/farmers'
    | '/inventory'
    | '/regions'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/analytics' | '/assistant' | '/farmers' | '/inventory' | '/regions'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/assistant'
    | '/farmers'
    | '/inventory'
    | '/regions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AssistantRoute: typeof AssistantRoute
  FarmersRoute: typeof FarmersRoute
  InventoryRoute: typeof InventoryRoute
  RegionsRoute: typeof RegionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/regions': {
      id: '/regions'
      path: '/regions'
      fullPath: '/regions'
      preLoaderRoute: typeof RegionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmers': {
      id: '/farmers'
      path: '/farmers'
      fullPath: '/farmers'
      preLoaderRoute: typeof FarmersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  AssistantRoute: AssistantRoute,
  FarmersRoute: FarmersRoute,
  InventoryRoute: InventoryRoute,
  RegionsRoute: RegionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
